blank_issues_enabled: false 
contact_links:
  - name: â“ PyRun Usage Question
    url: mailto:pyruncloud@gmail.com
    about: Please ask general usage questions here, not in the issue tracker.
  - name: ğŸ“š PyRun Documentation
    url: https://docs.pyrun.cloud
    about: Check the documentation for guides and tutorials.